[package]
name = "gameboy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.23"
blip_buf = "0.1"
cpal = "0.14.0"
clap = { version = "4.0.13", features = ["derive"] }